"""`GitHubRest`: the default GitHub client, REST everywhere except the PR operations public REST
lacks (cloud: the proxy's `ccr` routes; local: GraphQL), against a fake `gh api` runner."""
import inspect
import json
import re

import pytest

import sdlc_next as s
from sdlc_next import GhError, GitHub, GitHubRest

R = "repos/owner/repo"
FOOTER = "\n\n---\n_Generated by [Claude Code](https://claude.ai/code)_"


def _options(*names, start=100):
    return [{"id": start + i, "name": n} for i, n in enumerate(names)]


ORG_FIELDS = [
    {"id": 11, "node_id": "STAGE_FIELD_ID", "name": "Stage", "data_type": "single_select",
     "options": _options("Product", "Architecture", "Development", "PR Review", "LLD", "Testing")},
    {"id": 12, "node_id": "PIPELINE_STATUS_FIELD_ID", "name": "Pipeline Status",
     "data_type": "single_select",
     "options": _options("Todo", "In Progress", "Awaiting Human Review", "Needs Human",
                         "Feedback Received", "Done", start=200)},
    {"id": 13, "node_id": "PRIORITY_FIELD_ID", "name": "Priority", "data_type": "single_select",
     "options": _options("Urgent", "High", "Medium", "Low", start=300)},
    {"id": 14, "node_id": "EFFORT_FIELD_ID", "name": "Effort", "data_type": "single_select",
     "options": _options("High", "Medium", "Low", start=400)},
    {"id": 15, "node_id": "IFD_x", "name": "Start date", "data_type": "date"},
]


class Pages:
    """A multi-page response for `RestRunner`: page N is `pages[N-1]`, later pages `empty`."""

    def __init__(self, pages: list, empty=None):
        self.pages, self.empty = pages, ([] if empty is None else empty)


class RestRunner:
    """Fake `gh api`: canned JSON per (method, path); `--paginate --jq` emits one compact
    line per item like gh. Records `(method, path, fields)`; anything unscripted fails."""

    def __init__(self, routes: dict):
        self.routes = dict(routes)
        self.calls: list = []

    def __call__(self, argv):
        assert argv[:2] == ["gh", "api"], f"not a REST call: {argv}"
        assert "graphql" not in argv, f"GraphQL reached the REST provider: {argv}"
        args, method, jq, fields = argv[2:], "GET", None, []
        path = None
        i = 0
        while i < len(args):
            a = args[i]
            if a == "-X":
                method, i = args[i + 1], i + 2
            elif a == "--jq":
                jq, i = args[i + 1], i + 2
            elif a in ("-f", "-F"):
                fields.append((a, args[i + 1]))
                i += 2
            elif a == "--paginate":
                i += 1
            else:
                path, i = a, i + 1
        if fields and method == "GET":
            method = "POST"
        assert not path.startswith("repositories/"), f"numeric-id path: {path}"
        page = None
        m = re.search(r"[?&]page=(\d+)$", path)
        if m:  # `_api_items` paging: route on the path without `page`/the default per_page
            page, path = int(m.group(1)), path[:m.start()]
            if (method, path) not in self.routes and path.endswith("per_page=100"):
                path = path[:-len("per_page=100")].rstrip("?&")
        self.calls.append((method, path, fields))
        key = (method, path)
        if key not in self.routes:
            raise AssertionError(f"unscripted gh api call: {key} {fields}")
        resp = self.routes[key]
        if page is not None:  # a scripted list is one page; a list of pages is `Pages`
            if isinstance(resp, Pages):
                resp = resp.pages[page - 1] if page <= len(resp.pages) else resp.empty
            elif page > 1:
                resp = [] if isinstance(resp, list) else {k: ([] if isinstance(v, list) else v)
                                                           for k, v in resp.items()}
        if isinstance(resp, Exception):
            raise resp
        if jq is None:
            return json.dumps(resp) if resp is not None else ""
        if jq.endswith("[]"):
            items = resp if jq == ".[]" else resp[jq[1:-2]]
            return "".join(json.dumps(x) + "\n" for x in items)
        return f"{resp[jq[1:]]}\n"

    def writes(self):
        return [c for c in self.calls if c[0] != "GET"]


def _issue(n, **kw):
    return {"number": n, "id": 9000 + n, "node_id": f"I_{n}", "title": f"issue {n}",
            "body": "", "state": "open", "created_at": "2026-08-01T00:00:00Z",
            "labels": [], "type": None, "issue_field_values": [], "milestone": None,
            "parent_issue_url": None, "pull_request": None, **kw}


def _fv(field_id, name, option):
    return {"issue_field_id": field_id, "data_type": "single_select", "issue_field_name": name,
            "value": 1, "single_select_option": {"id": 1, "name": option}}


def _gh(routes):
    runner = RestRunner({("GET", "orgs/owner/issue-fields"): ORG_FIELDS, **routes})
    return GitHubRest(runner=runner), runner


# --- provider selection ---------------------------------------------------------------

@pytest.fixture
def cloud(monkeypatch):
    monkeypatch.setenv("CLAUDE_CODE_REMOTE", "true")


@pytest.mark.parametrize("env, cls", [
    ({}, GitHubRest),
    ({"CLAUDE_CODE_REMOTE": "true"}, GitHubRest),
    ({"SDLC_GITHUB_API": "graphql"}, GitHub),
    ({"CLAUDE_CODE_REMOTE": "true", "SDLC_GITHUB_API": "GraphQL"}, GitHub),
    ({"SDLC_GITHUB_API": "rest"}, GitHubRest),
])
def test_rest_is_the_provider_everywhere_unless_graphql_is_forced(monkeypatch, env, cls):
    for k, v in env.items():
        monkeypatch.setenv(k, v)
    assert type(s.get_work_item_provider(runner=RestRunner({}))) is cls


def test_an_invalid_sdlc_github_api_is_an_error(monkeypatch):
    monkeypatch.setenv("SDLC_GITHUB_API", "soap")
    with pytest.raises(GhError, match="SDLC_GITHUB_API='soap'"):
        s.get_work_item_provider(runner=RestRunner({}))


def test_github_api_reports_the_client_and_its_signal(monkeypatch):
    assert s.github_api() == {"api": "rest", "signal": "default"}
    monkeypatch.setenv("SDLC_GITHUB_API", "graphql")
    assert s.github_api() == {"api": "graphql", "signal": "SDLC_GITHUB_API"}


def test_every_graphql_or_gh_subcommand_method_is_overridden():
    # A GitHub method left on GraphQL or `gh issue|pr|label` would 403 behind the cloud proxy.
    # `_set_single_select` is reached only through the overridden `set_*_field` methods.
    leaky = []
    for name, fn in inspect.getmembers(GitHub, inspect.isfunction):
        src = inspect.getsource(fn)
        uses = ("self.graphql(" in src or '"gh", "issue"' in src or '"gh", "pr"' in src
                or '"gh", "label"' in src or '"gh", "run", "rerun"' in src)
        if uses and name not in GitHubRest.__dict__ and name != "_set_single_select":
            leaky.append(name)
    assert leaky == []


def test_graphql_itself_refuses_loudly_in_a_cloud_session(cloud):
    gh, _ = _gh({})
    with pytest.raises(GhError, match="GraphQL is not available"):
        gh.graphql("query { viewer { login } }")


# --- issue fields: config node ids -> REST field ids / option names ---------------------

def test_set_stage_maps_the_config_field_to_its_numeric_id_and_the_slug_to_the_option_name():
    gh, runner = _gh({("POST", f"{R}/issues/7/issue-field-values"): {}})
    gh.set_stage_field(7, "pr-review")
    gh.set_pipeline_status_field(7, "awaiting-human-review")
    gh.set_priority_field(7, "Urgent")
    gh.set_effort_field(7, "Low")
    assert [c[2] for c in runner.writes()] == [
        [("-F", "issue_field_values[][field_id]=11"), ("-f", "issue_field_values[][value]=PR Review")],
        [("-F", "issue_field_values[][field_id]=12"),
         ("-f", "issue_field_values[][value]=Awaiting Human Review")],
        [("-F", "issue_field_values[][field_id]=13"), ("-f", "issue_field_values[][value]=Urgent")],
        [("-F", "issue_field_values[][field_id]=14"), ("-f", "issue_field_values[][value]=Low")],
    ]
    # The org's fields are listed once per provider, not once per write.
    assert sum(1 for c in runner.calls if c[1] == "orgs/owner/issue-fields") == 1


def test_a_config_field_id_missing_from_the_org_fails_loudly():
    runner = RestRunner({("GET", "orgs/owner/issue-fields"): ORG_FIELDS[1:]})
    with pytest.raises(GhError, match="stageFieldId='STAGE_FIELD_ID' matches no field"):
        GitHubRest(runner=runner).set_stage_field(7, "lld")


def test_an_option_name_missing_from_the_org_field_fails_loudly():
    fields = [{**ORG_FIELDS[0], "options": _options("Product")}, *ORG_FIELDS[1:]]
    runner = RestRunner({("GET", "orgs/owner/issue-fields"): fields})
    with pytest.raises(GhError, match="no option named 'LLD'"):
        GitHubRest(runner=runner).set_stage_field(7, "lld")
    assert not runner.writes()


def test_option_names_match_case_insensitively_and_write_the_org_spelling():
    fields = [{**ORG_FIELDS[0], "options": _options("pr review")}]
    runner = RestRunner({("GET", "orgs/owner/issue-fields"): fields,
                         ("POST", f"{R}/issues/7/issue-field-values"): {}})
    GitHubRest(runner=runner).set_stage_field(7, "pr-review")
    assert ("-f", "issue_field_values[][value]=pr review") in runner.writes()[0][2]


def test_clearing_deletes_by_numeric_field_id_and_tolerates_an_unset_value():
    gh, runner = _gh({("DELETE", f"{R}/issues/7/issue-field-values/11"): {},
                      ("DELETE", f"{R}/issues/7/issue-field-values/12"):
                          GhError("gh: Not Found (HTTP 404)")})
    gh.clear_stage_and_status_fields(7)
    assert [c[1] for c in runner.writes()] == [f"{R}/issues/7/issue-field-values/11",
                                               f"{R}/issues/7/issue-field-values/12"]


def test_clearing_raises_any_other_failure():
    gh, _ = _gh({("DELETE", f"{R}/issues/7/issue-field-values/11"):
                 GhError("Write access to this GitHub API path is not permitted (HTTP 403)")})
    with pytest.raises(GhError, match="403"):
        gh.clear_stage_field(7)


def test_set_issue_type_patches_the_type_by_name():
    gh, runner = _gh({("PATCH", f"{R}/issues/7"): {}})
    gh.set_issue_type(7, "Epic")
    assert runner.writes() == [("PATCH", f"{R}/issues/7", [("-f", "type=Epic")])]
    with pytest.raises(GhError, match="issueTypeIds"):
        gh.set_issue_type(7, "Story")


# --- issue list / view ----------------------------------------------------------------

def test_issue_list_has_the_graphql_shape_and_drops_pull_requests():
    raw = [
        _issue(5, title="Epic", labels=[{"name": "type:epic", "color": "x"}],
               type={"id": 1, "name": "Epic"}, state="closed",
               issue_field_values=[_fv(11, "Stage", "LLD"), _fv(13, "Priority", "High"),
                                   {"issue_field_id": 15, "data_type": "date", "value": "x"}],
               milestone={"title": "M1"}, body="scope" + FOOTER,
               updated_at="2026-08-02T00:00:00Z"),
        _issue(6, parent_issue_url="https://api.github.com/repos/owner/repo/issues/5",
               issue_field_values=[{**_fv(12, None, "In Progress"), "issue_field_name": None}]),
        {**_issue(7), "pull_request": {"url": "x"}},
    ]
    gh, runner = _gh({("GET", f"{R}/issues?state=all&per_page=100&sort=created&direction=asc"):
                      raw})
    assert gh.issue_list() == [
        {"number": 5, "title": "Epic", "body": "scope", "createdAt": "2026-08-01T00:00:00Z",
         "updatedAt": "2026-08-02T00:00:00Z", "state": "CLOSED", "labels": [{"name": "type:epic"}], "issueType": {"name": "Epic"},
         "parent": None, "milestone": "M1", "fields": {"Stage": "LLD", "Priority": "High"}},
        {"number": 6, "title": "issue 6", "body": "", "createdAt": "2026-08-01T00:00:00Z",
         "updatedAt": None, "state": "OPEN", "labels": [], "issueType": None, "parent": {"number": 5},
         "milestone": None, "fields": {"Pipeline Status": "In Progress"}},
    ]
    # Fields come inline: no per-issue field call.
    assert not any("issue-field-values" in c[1] for c in runner.calls)


def test_stage_and_status_read_from_rest_fields():
    raw = [_issue(5, issue_field_values=[_fv(11, "Stage", "PR Review"),
                                         _fv(12, "Pipeline Status", "Needs Human")])]
    gh, _ = _gh({("GET", f"{R}/issues?state=all&per_page=100&sort=created&direction=asc"): raw})
    node = gh.issue_list()[0]
    assert (s.current_stage(node), s.pipeline_status(node)) == ("pr-review", "needs-human")


def test_issue_view_strips_the_proxy_footer_from_body_and_comments():
    marker = "<!-- role-comment: product -->\nhandoff"
    gh, _ = _gh({
        ("GET", f"{R}/issues/9"): _issue(9, body="body" + FOOTER, labels=[{"name": "a"}]),
        ("GET", f"{R}/issues/9/comments?per_page=100"): [
            {"node_id": "IC_1", "user": {"login": "bot"}, "body": marker + FOOTER,
             "created_at": "2026-08-02T00:00:00Z", "html_url": "u1"},
            {"node_id": "IC_2", "user": {"login": "op"}, "body": "a\n\n---\nhuman rule",
             "created_at": "2026-08-03T00:00:00Z", "html_url": "u2"}],
    })
    view = gh.issue_view(9)
    assert view["body"] == "body" and view["state"] == "OPEN"
    assert view["labels"] == [{"name": "a"}]
    assert [c["body"] for c in view["comments"]] == [marker, "a\n\n---\nhuman rule"]
    assert view["comments"][0]["author"] == {"login": "bot"}
    assert view["comments"][1]["createdAt"] == "2026-08-03T00:00:00Z"


@pytest.mark.parametrize("text, expected", [
    ("x" + FOOTER, "x"),
    ("x" + FOOTER + "\n", "x"),
    ("x" + FOOTER.replace("\n", "\r\n"), "x"),
    ("x\n\n---\nnot the footer", "x\n\n---\nnot the footer"),
    ("", ""),
    (None, None),
])
def test_strip_proxy_footer(text, expected):
    assert s.strip_proxy_footer(text) == expected


def test_issue_edit_adds_and_removes_labels_and_assignees():
    gh, runner = _gh({("POST", f"{R}/issues/9/labels"): [],
                      ("DELETE", f"{R}/issues/9/labels/sdlc%3Acloud"): [],
                      ("DELETE", f"{R}/issues/9/labels/gone%20label"):
                          GhError("Label does not exist (HTTP 404)"),
                      ("POST", f"{R}/issues/9/assignees"): {},
                      ("DELETE", f"{R}/issues/9/assignees"): {}})
    gh.issue_edit(9, add_labels=["a", "b"], remove_labels=["sdlc:cloud", "gone label"],
                  add_assignees=["op"], remove_assignees=["old"])
    assert runner.writes() == [
        ("POST", f"{R}/issues/9/labels", [("-f", "labels[]=a"), ("-f", "labels[]=b")]),
        ("DELETE", f"{R}/issues/9/labels/sdlc%3Acloud", []),
        ("DELETE", f"{R}/issues/9/labels/gone%20label", []),
        ("POST", f"{R}/issues/9/assignees", [("-f", "assignees[]=op")]),
        ("DELETE", f"{R}/issues/9/assignees", [("-f", "assignees[]=old")]),
    ]


def test_ensure_label_is_a_no_op_since_adding_a_label_creates_it():
    gh, runner = _gh({})
    gh.ensure_label("sdlc:cloud")
    assert runner.calls == []


@pytest.mark.parametrize("reason, rest", [("completed", "completed"),
                                          ("not planned", "not_planned")])
def test_issue_close_patches_state_and_reason(reason, rest):
    gh, runner = _gh({("PATCH", f"{R}/issues/9"): {}})
    gh.issue_close(9, reason)
    assert runner.writes() == [("PATCH", f"{R}/issues/9",
                                [("-f", "state=closed"), ("-f", f"state_reason={rest}")])]


def test_comments_post_on_issues_and_prs_alike():
    gh, runner = _gh({("POST", f"{R}/issues/9/comments"): {},
                      ("POST", f"{R}/issues/40/comments"): {}})
    gh.issue_comment(9, "hi")
    gh.pr_comment(40, "hey")
    assert [c[1:] for c in runner.writes()] == [(f"{R}/issues/9/comments", [("-f", "body=hi")]),
                                                (f"{R}/issues/40/comments", [("-f", "body=hey")])]


# --- sub-issues, parent, dependencies ---------------------------------------------------

def test_sub_issues_take_the_childs_numeric_id():
    gh, runner = _gh({("GET", f"{R}/issues/10"): _issue(10),
                      ("POST", f"{R}/issues/9/sub_issues"): {},
                      ("DELETE", f"{R}/issues/9/sub_issue"): {}})
    gh.add_sub_issue(9, 10)
    gh.remove_sub_issue(9, 10)
    assert runner.writes() == [("POST", f"{R}/issues/9/sub_issues", [("-F", "sub_issue_id=9010")]),
                               ("DELETE", f"{R}/issues/9/sub_issue", [("-F", "sub_issue_id=9010")])]


def test_epic_info_reads_type_parent_and_labels():
    gh, _ = _gh({("GET", f"{R}/issues/10"): _issue(
        10, type={"name": "Task"}, labels=[{"name": "type:task"}],
        parent_issue_url="https://api.github.com/repos/owner/repo/issues/9")})
    assert gh.issue_epic_info(10) == {"issueType": {"name": "Task"}, "parent": {"number": 9},
                                      "labels": [{"name": "type:task"}]}
    assert gh.classify_unit(10) == "task"


def test_blocked_by_lists_open_blockers_and_edges_take_numeric_ids():
    gh, runner = _gh({
        ("GET", f"{R}/issues/9/dependencies/blocked_by?per_page=100"):
            [_issue(3), _issue(4, state="closed")],
        ("GET", f"{R}/issues/9/dependencies/blocking?per_page=100"): [_issue(12)],
        ("GET", f"{R}/issues/3"): _issue(3),
        ("POST", f"{R}/issues/9/dependencies/blocked_by"): {},
        ("DELETE", f"{R}/issues/9/dependencies/blocked_by/9003"): {},
    })
    assert gh.blocked_by(9) == [3] and gh.blocking(9) == [12]
    gh.add_blocked_by(9, 3)
    gh.remove_blocked_by(9, 3)
    assert runner.writes() == [
        ("POST", f"{R}/issues/9/dependencies/blocked_by", [("-F", "issue_id=9003")]),
        ("DELETE", f"{R}/issues/9/dependencies/blocked_by/9003", [])]


# --- pull requests -----------------------------------------------------------------------

def _pr(n, **kw):
    return {"number": n, "title": f"pr {n}", "state": "open", "merged_at": None, "draft": True,
            "body": "", "created_at": "2026-08-05T00:00:00Z", "html_url": f"https://x/pull/{n}",
            "head": {"ref": "issue-9", "sha": "abc123"}, "base": {"ref": "epic-5"},
            "merge_commit_sha": "test-merge-sha", **kw}


def test_pr_create_ready_and_merge(cloud):
    gh, runner = _gh({("POST", f"{R}/pulls"): {"number": 41},
                      ("POST", f"{R}/pulls/41/ccr/ready_for_review"): {},
                      ("PUT", f"{R}/pulls/41/merge"): {"merged": True}})
    assert gh.pr_create("epic-5", "issue-9", "T", "B", draft=True) == 41
    gh.pr_ready(41)
    gh.pr_merge(41, delete_branch=True, method="squash", match_head="abc123")
    assert runner.writes() == [
        ("POST", f"{R}/pulls", [("-f", "title=T"), ("-f", "body=B"), ("-f", "head=issue-9"),
                                ("-f", "base=epic-5"), ("-F", "draft=true")]),
        ("POST", f"{R}/pulls/41/ccr/ready_for_review", []),
        ("PUT", f"{R}/pulls/41/merge", [("-f", "merge_method=squash"), ("-f", "sha=abc123")]),
    ]


def test_pr_view_maps_fields_states_and_strips_the_footer():
    gh, _ = _gh({("GET", f"{R}/pulls/41"): _pr(41, body="Closes #9" + FOOTER),
                 ("GET", f"{R}/pulls/42"): _pr(42, state="closed",
                                                merged_at="2026-08-06T00:00:00Z"),
                 ("GET", f"{R}/pulls/43"): _pr(43, state="closed"),
                 ("GET", f"{R}/issues/41/comments?per_page=100"): [
                     {"node_id": "IC", "user": {"login": "op"}, "body": "ok" + FOOTER,
                      "created_at": "t", "html_url": "u"}]})
    assert gh.pr_view(41, "state,mergedAt,headRefName,baseRefName,body,headRefOid,isDraft") == {
        "state": "OPEN", "mergedAt": None, "headRefName": "issue-9", "baseRefName": "epic-5",
        "body": "Closes #9", "headRefOid": "abc123", "isDraft": True}
    assert gh.pr_view(41, "comments,createdAt")["comments"][0]["body"] == "ok"
    assert gh.pr_view(41, "mergeCommit") == {"mergeCommit": None}
    assert gh.pr_view(42, "state,mergeCommit") == {"state": "MERGED",
                                                    "mergeCommit": {"oid": "test-merge-sha"}}
    assert gh.pr_view(43) == {"state": "CLOSED", "mergedAt": None}


def test_prs_for_a_branch_filter_by_exact_head_and_merged_state():
    path = f"{R}/pulls?head=owner:issue-9&state=closed&per_page=100"
    gh, _ = _gh({
        ("GET", path): [_pr(40, state="closed", merged_at="t"), _pr(39, state="closed"),
                        _pr(38, head={"ref": "issue-99", "sha": "x"}, merged_at="t")],
        ("GET", f"{R}/pulls?head=owner:issue-9&state=all&per_page=100"):
            [_pr(41), _pr(40, state="closed", merged_at="t")],
    })
    assert gh.pr_list_for_branch("issue-9", state="merged") == [
        {"number": 40, "isDraft": True, "headRefName": "issue-9", "title": "pr 40",
         "url": "https://x/pull/40"}]
    assert gh.pr_heads_for_branch("issue-9") == [
        {"number": 41, "state": "OPEN", "headRefOid": "abc123"},
        {"number": 40, "state": "MERGED", "headRefOid": "abc123"}]


def test_pr_add_label_adds_it_on_the_issue_side():
    gh, runner = _gh({("POST", f"{R}/issues/41/labels"): []})
    gh.pr_add_label(41, "sdlc:gate")
    assert runner.writes() == [("POST", f"{R}/issues/41/labels", [("-f", "labels[]=sdlc:gate")])]


def _run(name, status, conclusion, suite, app="github-actions", job=7):
    return {"name": name, "status": status, "conclusion": conclusion,
            "html_url": f"https://github.com/owner/repo/actions/runs/{suite * 10}/job/{job}",
            "details_url": f"https://github.com/owner/repo/actions/runs/{suite * 10}/job/{job}",
            "check_suite": {"id": suite}, "app": {"slug": app}}


def test_pr_checks_map_check_runs_and_statuses_to_gh_buckets_with_workflow_names():
    gh, _ = _gh({
        ("GET", f"{R}/pulls/41"): _pr(41),
        ("GET", f"{R}/commits/abc123/check-runs?per_page=100"): {"check_runs": [
            _run("test", "completed", "success", 1),
            _run("lint", "completed", "failure", 2, job=8),
            _run("e2e", "in_progress", None, 3),
            _run("skip", "completed", "skipped", 1),
            _run("old", "completed", "cancelled", 2),
            _run("ext", "completed", "neutral", 4, app="other-ci")]},
        ("GET", f"{R}/actions/runs?head_sha=abc123&per_page=100"): {"workflow_runs": [
            {"id": 10, "check_suite_id": 1, "name": "Backend CI"},
            {"id": 20, "check_suite_id": 2, "name": "Frontend CI"},
            {"id": 30, "check_suite_id": 3, "name": "E2E"}]},
        ("GET", f"{R}/commits/abc123/status"): {"statuses": [
            {"context": "deploy", "state": "pending", "target_url": "https://ci"},
            {"context": "sec", "state": "error", "target_url": None}]},
    })
    checks = gh.pr_checks(41)
    assert [(c["name"], c["state"], c["bucket"], c["workflow"]) for c in checks] == [
        ("test", "SUCCESS", "pass", "Backend CI"),
        ("lint", "FAILURE", "fail", "Frontend CI"),
        ("e2e", "IN_PROGRESS", "pending", "E2E"),
        ("skip", "SKIPPED", "skipping", "Backend CI"),
        ("old", "CANCELLED", "cancel", "Frontend CI"),
        ("ext", "NEUTRAL", "skipping", ""),
        ("deploy", "PENDING", "pending", ""),
        ("sec", "ERROR", "fail", ""),
    ]
    # The link keeps the Actions run/job ids `rerun-checks` and the failure excerpt parse.
    assert s._check_run_and_job(checks[1]) == (20, 8)
    assert s.workflow_check_state(checks, "Backend CI") == "passing"
    assert s.checks_status(checks) == "failed"


def test_pr_checks_with_nothing_reported_is_empty():
    gh, runner = _gh({("GET", f"{R}/pulls/41"): _pr(41),
                      ("GET", f"{R}/commits/abc123/check-runs?per_page=100"): {"check_runs": []},
                      ("GET", f"{R}/commits/abc123/status"): {"statuses": []}})
    assert gh.pr_checks(41) == []
    assert not any("actions/runs" in c[1] for c in runner.calls)


def test_rerun_failed_posts_the_actions_rerun():
    gh, runner = _gh({("POST", f"{R}/actions/runs/20/rerun-failed-jobs"): {}})
    gh.run_rerun_failed(20)
    assert runner.writes() == [("POST", f"{R}/actions/runs/20/rerun-failed-jobs", [])]


def test_delete_branch_failure_names_the_proxy():
    gh, _ = _gh({("DELETE", f"{R}/git/refs/heads/issue-9"):
                 GhError("Write access to this GitHub API path is not permitted (HTTP 403)")})
    with pytest.raises(GhError, match="cloud GitHub proxy refuses ref deletes"):
        gh.delete_branch("issue-9")


# --- review threads (ccr) -----------------------------------------------------------------

def test_review_threads_round_trip_through_resolve_thread(cloud):
    gh, runner = _gh({
        ("GET", f"{R}/pulls/41/ccr/review_threads"): [
            {"id": "PRRT_1", "is_resolved": False, "comments": [
                {"id": 555, "body": "fix this" + FOOTER, "user": {"login": "op"}}]},
            {"id": "PRRT_2", "is_resolved": True, "comments": [{"id": 556, "body": "done"}]}],
        ("POST", f"{R}/pulls/41/comments/555/replies"): {},
        ("POST", f"{R}/pulls/41/ccr/comments/555/resolve"): {},
    })
    threads = gh.unresolved_review_threads(41)
    assert threads == [{"id": "ccr:41:555", "isResolved": False, "comments": {"nodes": [
        {"body": "fix this", "author": {"login": "op"}}]}}]
    assert s.cmd_resolve_thread(gh, threads[0]["id"], reply="done") == {
        "thread": "ccr:41:555", "replied": True, "resolved": True}
    assert [c[1] for c in runner.writes()] == [f"{R}/pulls/41/comments/555/replies",
                                               f"{R}/pulls/41/ccr/comments/555/resolve"]


def test_a_graphql_thread_id_is_refused_in_a_cloud_session(cloud):
    gh, runner = _gh({})
    with pytest.raises(GhError, match="not a cloud-session id"):
        gh.resolve_review_thread("PRRT_kwDOabc")
    assert runner.calls == []


# --- local session: the no-REST-path operations stay on GraphQL ----------------------------

class LocalRunner(RestRunner):
    """`RestRunner` that also answers the GraphQL/`gh pr ready` calls a local session makes."""

    def __init__(self, routes, graphql=None):
        super().__init__(routes)
        self.graphql = graphql or {}
        self.other: list = []

    def __call__(self, argv):
        if argv[:3] == ["gh", "api", "graphql"] or argv[:3] == ["gh", "pr", "ready"]:
            self.other.append(argv)
            query = next((a for a in argv if a.startswith("query=")), "")
            for needle, resp in self.graphql.items():
                if needle in query:
                    return json.dumps({"data": resp})
            return json.dumps({"data": {}})
        return super().__call__(argv)


def test_locally_pr_ready_uses_gh_pr_ready_not_the_proxy_route():
    runner = LocalRunner({})
    GitHubRest(runner=runner).pr_ready(41)
    assert runner.other == [["gh", "pr", "ready", "41", "--repo", "owner/repo"]]
    assert runner.calls == []


def test_locally_review_threads_list_reply_and_resolve_over_graphql():
    threads = {"repository": {"pullRequest": {"reviewThreads": {"nodes": [
        {"id": "PRRT_1", "isResolved": False, "comments": {"nodes": []}},
        {"id": "PRRT_2", "isResolved": True, "comments": {"nodes": []}}]}}}}
    runner = LocalRunner({}, graphql={"reviewThreads": threads})
    gh = GitHubRest(runner=runner)
    assert [t["id"] for t in gh.unresolved_review_threads(41)] == ["PRRT_1"]
    assert s.cmd_resolve_thread(gh, "PRRT_1", reply="done")["resolved"] is True
    queries = [next(a for a in c if a.startswith("query=")) for c in runner.other]
    assert "reviewThreads" in queries[0]
    assert "addPullRequestReviewThreadReply" in queries[1]
    assert "resolveReviewThread" in queries[2] and "threadId=PRRT_1" in runner.other[2]
    assert runner.calls == []


def test_locally_every_other_operation_still_goes_over_rest():
    runner = LocalRunner({("GET", "orgs/owner/issue-fields"): ORG_FIELDS,
                          ("POST", f"{R}/issues/7/issue-field-values"): {},
                          ("PUT", f"{R}/pulls/41/merge"): {}})
    gh = GitHubRest(runner=runner)
    gh.set_stage_field(7, "lld")
    gh.pr_merge(41)
    assert runner.other == [] and len(runner.writes()) == 2


# --- labels -------------------------------------------------------------------------------

def test_pr_remove_label_deletes_it_through_the_issues_endpoint():
    gh, runner = _gh({("DELETE", f"{R}/issues/40/labels/sdlc%3Agate"): None})
    gh.pr_remove_label(40, "sdlc:gate")
    assert runner.writes() == [("DELETE", f"{R}/issues/40/labels/sdlc%3Agate", [])]


def test_api_items_pages_by_page_number_never_by_link_following():
    # The cloud proxy rejects `repositories/{id}/...`, the form GitHub's `Link: next` uses, so
    # `gh api --paginate` broke the first issue listing of a real cloud run. Page by `page=N`.
    full = [{"n": i} for i in range(100)]
    runner = RestRunner({("GET", f"repos/{s.REPO}/things"): Pages([full, full, [{"n": "last"}]])})
    gh = GitHubRest(runner=runner)
    items = gh._api_items(f"repos/{s.REPO}/things")
    assert len(items) == 201 and items[-1] == {"n": "last"}
    assert [c[1] for c in runner.calls] == [f"repos/{s.REPO}/things"] * 3
    assert not any("--paginate" in str(c) for c in runner.calls)


def test_api_items_reads_a_keyed_list_and_stops_on_a_short_page():
    runner = RestRunner({("GET", f"repos/{s.REPO}/commits/abc/check-runs?per_page=100"):
                         {"total_count": 2, "check_runs": [{"id": 1}, {"id": 2}]}})
    gh = GitHubRest(runner=runner)
    assert gh._api_items(f"repos/{s.REPO}/commits/abc/check-runs?per_page=100", ".check_runs[]") == [
        {"id": 1}, {"id": 2}]
    assert len(runner.calls) == 1


def test_a_config_snapshot_of_the_org_fields_replaces_the_org_endpoint(monkeypatch):
    # The cloud's GitHub proxy allows only repo-scoped paths: `orgs/{owner}/issue-fields`
    # 403s, which stopped the first real cloud run at its first field write. With
    # projectFields.issueFieldsRest set, the org endpoint is never called.
    monkeypatch.setitem(s._PF, "issueFieldsRest", ORG_FIELDS)
    runner = RestRunner({("POST", f"{R}/issues/7/issue-field-values"): {}})
    GitHubRest(runner=runner).set_stage_field(7, "lld")
    assert not any(c[1].startswith("orgs/") for c in runner.calls)
    assert runner.writes()[0][1] == f"{R}/issues/7/issue-field-values"


def test_a_stale_snapshot_says_so():
    import sdlc_next
    runner = RestRunner({})
    gh = GitHubRest(runner=runner)
    gh._org_fields = ORG_FIELDS[1:]
    sdlc_next._PF["issueFieldsRest"] = ORG_FIELDS[1:]
    try:
        with pytest.raises(GhError, match="issueFieldsRest .stale"):
            gh.set_stage_field(7, "lld")
    finally:
        sdlc_next._PF.pop("issueFieldsRest")


def test_show_issue_fields_prints_the_snapshot_shape():
    runner = RestRunner({("GET", "orgs/owner/issue-fields"): [
        {**ORG_FIELDS[0], "data_type": "single_select", "extra": 1}]})
    out = s.cmd_show_issue_fields(runner=runner)
    assert out == [{"id": ORG_FIELDS[0]["id"], "node_id": ORG_FIELDS[0]["node_id"],
                    "name": ORG_FIELDS[0]["name"],
                    "options": [{"id": o["id"], "name": o["name"]}
                                for o in ORG_FIELDS[0]["options"]]}]
